CREATE TABLE [dbo].[Client]
(
	[Id] INT IDENTITY (1, 1) NOT NULL,
    [Orgnummer]       NVARCHAR (50) NOT NULL,
    [Password]      NVARCHAR (50) NOT NULL,
    [FirmaNavn] NVARCHAR(50),
    [GateNavn] NVARCHAR(50),
    [HusNummer] INT,
    [HusBokStav] NVARCHAR(20),
    [PostNummer] INT,
    [Sted] NVARCHAR(50),
    [Epost] NVARCHAR(20),
    [KontaktNavn] NVARCHAR(30),
    [KontaktEpost] NVARCHAR(20),
    [KontaktTlfnr] NVARCHAR(30),
    [TekniskKontaktNavn] NVARCHAR(20),
    [TekniskKontaktEpost] NVARCHAR(30),
    [TekniskKontaktTlfnr] NVARCHAR(30),
    [Id_abonementype] int not null,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([Id_abonementype]) REFERENCES [dbo].[Abonementype](Id) ON DELETE CASCADE,
)
