//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeliaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Fakturaoppsetts = new HashSet<Fakturaoppsett>();
        }
    
        public int Id { get; set; }
        public string Orgnummer { get; set; }
        public string Password { get; set; }
        public string FirmaNavn { get; set; }
        public string GateNavn { get; set; }
        public Nullable<int> HusNummer { get; set; }
        public string HusBokStav { get; set; }
        public Nullable<int> PostNummer { get; set; }
        public string Sted { get; set; }
        public string Epost { get; set; }
        public string KontaktNavn { get; set; }
        public string KontaktEpost { get; set; }
        public string KontaktTlfnr { get; set; }
        public string TekniskKontaktNavn { get; set; }
        public string TekniskKontaktEpost { get; set; }
        public string TekniskKontaktTlfnr { get; set; }
        public int Id_abonementype { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fakturaoppsett> Fakturaoppsetts { get; set; }
        public virtual Abonementype Abonementype { get; set; }
    }
}
