//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeliaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id { get; set; }
        public string Orgnummer { get; set; }
        public string Password { get; set; }
        public string FirmaNavn { get; set; }
        public string GateNavn { get; set; }
        public Nullable<int> HusNummer { get; set; }
        public string HusBokStav { get; set; }
        public Nullable<int> PostNummer { get; set; }
        public string Sted { get; set; }
        public string Epost { get; set; }
        public string KontaktNavn { get; set; }
        public string KontaktEpost { get; set; }
        public string KontaktTlfnr { get; set; }
        public string TekniskKontaktNavn { get; set; }
        public string TekniskKontaktEpost { get; set; }
        public string TekniskKontaktTlfnr { get; set; }
    }
}
