//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeliaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionType
    {
        public int Id { get; set; }
        public int Id_abom { get; set; }
        public int Id_type { get; set; }
    
        public virtual Abonementype Abonementype { get; set; }
        public virtual Type Type { get; set; }
    }
}
