//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeliaMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Nummer
    {
        [Required]
        [TelefonnummerCheck]
        public string Telefonnummer { get; set; }
        [Required]
        public string Abonnementstype { get; set; }
        [Required]
        [StringLength(25)]
        public string Fornavn { get; set; }
        [Required]
        [StringLength(35)]
        public string Etternavn { get; set; }
        [StringLength(35)]
        public string Bedrift_som_skal_faktureres { get; set; }
        public string c_o_adresse_for_SIM_levering { get; set; }
        public string Gateadresse_SIM_Skal_sendes_til { get; set; }
        public Nullable<int> Hus_nummer { get; set; }
        [StringLength(20)]
        public string Hus_bokstav { get; set; }
        public Nullable<int> post_nr_ { get; set; }
        public string Post_sted { get; set; }
        [Display(Name = "Epost - Sporings_informasjon")]
        [Required(ErrorMessage = "This email address is required!")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Epost_for_sporings_informasjon { get; set; }
        [Display(Name = "Epost")]
        [Required(ErrorMessage = "This email address is required!")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Epost { get; set; }
        [Required]
        [StringLength(30)]
        public string Kostnadsted { get; set; }
        public Nullable<int> Tilleggsinfo_ansatt_ID { get; set; }
        [DataSIM2]
        public Nullable<int> Ekstra_talesim_ { get; set; }
        [DataSIM5]
        public Nullable<int> Ekstra_datasim { get; set; }
        public int ID { get; set; }
    
        public virtual Fakturaoppsett Fakturaoppsett { get; set; }
    }
}
