//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeliaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nummer
    {
        public string Telefonnummer { get; set; }
        public string Abonnementstype { get; set; }
        public string Fornavn { get; set; }
        public string Etternavn { get; set; }
        public string Bedrift_som_skal_faktureres { get; set; }
        public string c_o_adresse_for_SIM_levering { get; set; }
        public string Gateadresse_SIM_Skal_sendes_til { get; set; }
        public Nullable<int> Hus_nummer { get; set; }
        public string Hus_bokstav { get; set; }
        public Nullable<int> post_nr_ { get; set; }
        public string Post_sted { get; set; }
        public string Epost_for_sporings_informasjon { get; set; }
        public string Epost { get; set; }
        public string Kostnadsted { get; set; }
        public Nullable<int> Tilleggsinfo_ansatt_ID { get; set; }
        public Nullable<int> Ekstra_talesim_ { get; set; }
        public Nullable<int> Ekstra_datasim { get; set; }
        public int ID { get; set; }
        public string Orgnummer { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Pending { get; set; }
    
        public virtual Fakturaoppsett Fakturaoppsett { get; set; }
    }
}
