//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeliaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nummer
    {
        public string Telefonnummer { get; set; }
        public string Abonnementstype { get; set; }
        public string Fornavn { get; set; }
        public string Etternavn { get; set; }
        public string Bedrift_som_skal_faktureres { get; set; }
        public string c_o_adresse_for_SIM_levering { get; set; }
        public string Gateadresse_SIM_Skal_sendes_til { get; set; }
        public Nullable<int> Hus_nummer { get; set; }
        public string Hus_bokstav { get; set; }
        public Nullable<int> post_nr_ { get; set; }
        public string Post_sted { get; set; }
        public string Epost_for_sporings_informasjon { get; set; }
        public string Epost { get; set; }
        public string Kostnadsted { get; set; }
        public Nullable<int> Tilleggsinfo_ansatt_ID { get; set; }
        public Nullable<int> Ekstra_talesim_ { get; set; }
        public Nullable<int> Ekstra_datasim { get; set; }
        public int ID { get; set; }
        public string Orgnummer { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Pending { get; set; }
        public string Katalogoppforing { get; set; }
        public Nullable<System.DateTime> Porteringsdatoog_tid { get; set; }
        public Nullable<bool> Binding { get; set; }
        public Nullable<int> Postnummer { get; set; }
        public Nullable<int> Antall_TrillingSIM { get; set; }
        public Nullable<int> allDataSIM { get; set; }
        public Nullable<bool> Manuell_Top_up { get; set; }
        public Nullable<bool> Sperre_Top_up { get; set; }
        public Nullable<bool> Norden { get; set; }
        public Nullable<bool> Tale_og_SMS_til_EU { get; set; }
        public string TBN { get; set; }
        public Nullable<int> HovedSIM { get; set; }
        public Nullable<int> TrillingSIM1 { get; set; }
        public Nullable<int> TrillingSIM2 { get; set; }
        public Nullable<int> DataSIM1 { get; set; }
        public Nullable<int> DataSIM2 { get; set; }
        public Nullable<int> DataSIM3 { get; set; }
        public Nullable<int> DataSIM4 { get; set; }
        public Nullable<int> DataSIM5 { get; set; }
        public string DeliveryMethodCode { get; set; }
        public string DeliveryStreetName { get; set; }
        public string DeliveryStreetNumber { get; set; }
        public string DeliveryStreetSuffix { get; set; }
        public string DeliveryCity { get; set; }
        public string DeliveryZIP { get; set; }
        public string DeliveryCountryCode { get; set; }
        public string DeliveryContractEmail { get; set; }
        public string DeliveryContractCountryCode { get; set; }
        public string DeliveryContractLocalNumber { get; set; }
        public string DeliveryIndividualFirstName { get; set; }
        public string DeliveryIndividualLastName { get; set; }
    
        public virtual Fakturaoppsett Fakturaoppsett { get; set; }
    }
}
