//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeliaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postnummer
    {
        public int Id { get; set; }
        public string PostNr { get; set; }
        public string Poststed { get; set; }
        public string Kommunenummer { get; set; }
        public string Kommunenavn { get; set; }
        public string Kategory { get; set; }
        public string Land { get; set; }
    }
}
